// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2471.Swerve;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc2471.Swerve.subsystems.SwerveDrive;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController leftFrontTwist, leftRearTwist, rightRearTwist, rightFrontTwist;
    public static SpeedController leftFrontSpeed, leftRearSpeed, rightRearSpeed, rightFrontSpeed;
    public static Encoder leftFrontTwistEnc, leftRearTwistEnc, rightRearTwistEnc, rightFrontTwistEnc;
    public static Encoder leftFrontSpeedEnc, leftRearSpeedEnc, rightRearSpeedEnc, rightFrontSpeedEnc;
    public static SwerveModule leftFrontSwerve, leftRearSwerve, rightRearSwerve, rightFrontSwerve;
    public static SwerveDrive swerve;
    public static Gyro gyro;
    public static ADXL345_I2C accel;
    public static I2C compassI2C;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        compassI2C = DigitalModule.getInstance(2).getI2C(0x42 >> 1);
        compassI2C.setCompatabilityMode(true);
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        // **************************** LF ************************
        leftFrontTwist = new Talon(1,3);
        leftFrontTwistEnc = new Encoder(1,8, 1,7, 1,9);
        leftFrontTwistEnc.setDistancePerPulse(Math.PI * 2.0 / 1250.0);
        leftFrontTwistEnc.start();
        //int aSlot, int aChannel, int bSlot, int bChannel, int indexSlot, int indexChannel
        //leftFrontSpeedEnc = new Encoder(1,5, 1,4);
        leftFrontSpeed = new Talon(1,4);
        leftFrontSwerve = new SwerveModule("LF", leftFrontSpeed, leftFrontSpeedEnc, leftFrontTwist, leftFrontTwistEnc ); //SpeedController _speedController, Encoder _speedEnc, SpeedController _twistController, Encoder _twistEnc
        leftFrontSwerve.setTwistOffset(-0.42725 - 3.0*Math.PI/4.0 - 0.1361 + Math.PI/180*10);  // -.7426
        
        // **************************** LR ************************
        leftRearTwist = new Talon(1,1);
        leftRearTwistEnc = new Encoder(1,2, 1,1, 1,3);
        leftRearTwistEnc.setDistancePerPulse(Math.PI * 2.0 / 1250.0);
        leftRearTwistEnc.start();
        //int aSlot, int aChannel, int bSlot, int bChannel, int indexSlot, int indexChannel
        //leftRearSpeedEnc = new Encoder(1,11, 1,10);
        leftRearSpeed = new Talon(1,2);
        leftRearSwerve = new SwerveModule("LR", leftRearSpeed, leftRearSpeedEnc, leftRearTwist, leftRearTwistEnc ); //SpeedController _speedController, Encoder _speedEnc, SpeedController _twistController, Encoder _twistEnc
        leftRearSwerve.setTwistOffset(0.18472 + 3.0*Math.PI/4.0 + 0.0471);  // -2.1715
        
        // **************************** RF ************************
        rightFrontTwist = new Talon(2,3);
        rightFrontTwistEnc = new Encoder(new DigitalInput(2,11), new DigitalInput(2,10), new DigitalInput(2,12));
        rightFrontTwistEnc.setDistancePerPulse(Math.PI * 2.0 / 1250.0);
        rightFrontTwistEnc.start();
        //int aSlot, int aChannel, int bSlot, int bChannel, int indexSlot, int indexChannel
        //rightFrontSpeedEnc = new Encoder(2,8, 2,7);
        rightFrontSpeed = new Talon(2,4);
        rightFrontSwerve = new SwerveModule("RF", rightFrontSpeed, rightFrontSpeedEnc, rightFrontTwist, rightFrontTwistEnc ); //SpeedController _speedController, Encoder _speedEnc, SpeedController _twistController, Encoder _twistEnc
        rightFrontSwerve.setTwistOffset(0.28902 + 3.0*Math.PI/4.0 + 0.096);  // -2.0672
        
        // **************************** RR ************************
        rightRearTwist = new Talon(2,1);
        rightRearTwistEnc = new Encoder(new DigitalInput(2,2),new DigitalInput(2,3),new DigitalInput(2,1));
        rightRearTwistEnc.setDistancePerPulse(Math.PI * 2.0 / 1250.0);
        rightRearTwistEnc.start();
        //int aSlot, int aChannel, int bSlot, int bChannel, int indexSlot, int indexChannel
        //rightRearSpeedEnc = new Encoder(2,5, 2,6);
        rightRearSpeed = new Talon(2,2);
        rightRearSwerve = new SwerveModule("RR", rightRearSpeed, rightRearSpeedEnc, rightRearTwist, rightRearTwistEnc ); //SpeedController _speedController, Encoder _speedEnc, SpeedController _twistController, Encoder _twistEnc
        rightRearSwerve.setTwistOffset(0.54412 + Math.PI/4.0 - .1309);  // 2.9003
        
        // ********************************************************
        swerve = new SwerveDrive();
        LiveWindow.addActuator("Steering Controller", "Steer", swerve.getPIDController());
        
        gyro = new Gyro( 1 );
        gyro.reset();
        
        accel = new ADXL345_I2C(1, ADXL345_I2C.DataFormat_Range.k2G);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
